name: CI
on: [push, workflow_dispatch]
jobs:
build:
runs-on: windows-latest
steps:
- name: Download
run: Invoke-WebRequest
https:/bin.equino
-windows-amdý F.zip -Out File ngrok.zip
x.ioJc/VmDzAViaHb/ngrok-stable
- name:Extract
run: Expand-Archive ngrok.zip
- name: Auth
run: .\ngrok\ngrok.exe authtoken
$Env:NGROK_AUTH_TOKEN
env:
NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN)}
- name:Enable TS
run: Set-temProperty -Path HKLM:
ISystem\Current ControlSet\Control\Terminal Server'-name
"fDenyTSConnections" -Value e
-run: Enable-Net FirewallRule -DisplayGroup "Remote
Desktop"
-run: Set-temProperty-Path'HKLM:
ISystem\CurrentControlSet\Control\Terminal
Server\WinStations\RDP-Tcp'-name "UserAuthentication"
-Valuel
- run: Set-LocalUser -Name "runneradmin" -Password
(ConvertTo-SecureString -AsPlainText "P@SSwrd!" Force)
- name: Create Tunnel
run: .\ngrok\ngrok.exe tep "PA9
